required-players: 2
cooldown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 0
  y: 70
  z: 0
  yaw: 180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 0
    y: 70
    z: 0
    yaw: 180
    pitch: 0

